### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [ealba727/Capstone#5]
_Grade:_ **Meets Expectations**

Some good work implementing a page that follows the structure of the project specification.

Some things to pay attention to: 
* Be sure to specify `font-family` correctly
* Consider using `<a>` elements for the navigation links
* Be more precise over indentation
    * The indentation should reflect the parent-child relationships between elements
* Remember to use list elements (e.g. `<ul>`) to contain list item elements `<li>`
* Prefer semantic elements over `<div>`s with a class name
    * This gives more formal structure to your document

Further Reading: 
* https://learn.shayhowe.com/html-css/writing-your-best-code/
* https://css-tricks.com/the-difference-between-id-and-class/
* http://www.apaddedcell.com/div-itis-what-it-and-how-avoid-it
* https://internetingishard.com/html-and-css/semantic-html/

Keep on Coding.

**Comment by ealba727** [comment]
they you! great review, super helpful!
